name: Awaker Workflow

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  run-awaker:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirments.txt

    - name: Run awaker script
      env:
        FROM_EMAIL_ID: ${{ secrets.FROM_EMAIL_ID }}
        EMAIL_PASS: ${{ secrets.EMAIL_PASS }}
        TO_EMAIL_ID: ${{ secrets.TO_EMAIL_ID }}
      run: |
        python main.py
